language: node_js
node_js:
  - "4.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project games --token $FIREBASE_TOKEN
  - echo "Deployed!"
